apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  labels:
    app: {{ .Values.service.serviceLabel }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "5"
spec:
  type: {{ .Values.service.serviceType }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: {{ .Values.service.portName }}
  selector:
    identity: {{ .Values.service.selectorIdentity }}
