apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-egress-svc.fullname" . }}
  labels:
    {{- include "nginx-egress.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "6"
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports.grpc }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: grpc-{{ . }}
    {{- end }}
    {{- range .Values.service.ports.http }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: http-{{ . }}
    {{- end }}
  sessionAffinity: ClientIP
  topologyKeys:
  {{- range .Values.service.topologyKeys }}
  - {{ . }}
  {{- end }}
  selector:
    {{- include "nginx-egress.selectorLabels" . | nindent 4 }}
