deploymentName: configdb-deploy
deploymentLabel: configdb-deploy
replicaCount: 1
deploymentSelectorLabel: configdb-pod
deploymentTemplateLabel: configdb-pod
deploymentTemplateIdentity: configdb-pod

mariadb:
  containerName: mariadb
  image:
    repository: ""
    image: mariadb
    tag: ""
  imagePullPolicy: Always
  containerPort: 3306
  liveliness:
      initialDelaySec: 120
      periodSec: 10
      timeoutSec: 1
      sucessThreshold: 1
      failureThreshold: 3
  readiness:
      initialDelaySec: 30
      periodSec: 10
      timeoutSec: 1
      successThreshold: 1
      failureThreshold: 3
  env:
      sqlRootPassword: root
      dbName: configdb

configdb:
  containerName: configdb
  image:
    repository: ""
    image: configdb
    tag: ""
  imagePullPolicy: Always
  containerPort: 50055
  env:
      dbUserName: root
      dbUserPassword: root
      dbName: configdb
      dbService: localhost
      dbListenPort: 50055
      dbPort: 3306
